//! Guards the command ACL chain against drift.
//!
//! Exposing a Tauri command to the UI requires five separate lists to agree:
//!
//! ```text
//! REGISTERED_COMMANDS (orange-domain)
//!   -> build.rs generates permissions/autogenerated/<command>.toml
//!   -> capabilities/*.json grants "allow-<kebab-name>"
//!   -> the runtime allows the invoke
//! ```
//!
//! plus `invoke_handler!` in src/lib.rs and `COMMANDS` in ../src/ipc.ts.
//!
//! A command missing from any link still compiles and still appears in the UI,
//! but Tauri rejects the invoke with a bare string rather than a structured
//! `CommandError`. The shell cannot parse that, so it falls back to
//! "操作未完成，请稍后重试" -- a message that points nowhere. Twelve commands
//! were broken this way simultaneously before these assertions existed.
//!
//! These tests parse the sources as text because the lists span Rust, JSON and
//! TypeScript, and no single compiler sees all of them.

use std::{collections::BTreeSet, fs, path::PathBuf};

fn repository_path(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative)
}

fn read(relative: &str) -> String {
    let path = repository_path(relative);
    fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()))
}

/// Extracts the command identifiers from the desktop `generate_handler!` block.
///
/// The mobile build registers a much smaller list from a second macro
/// invocation; only the first (desktop) block is relevant here.
fn desktop_handler_commands() -> BTreeSet<String> {
    let source = read("src/lib.rs");
    let start = source
        .find("generate_handler![")
        .expect("src/lib.rs must contain a generate_handler! block");
    let body = &source[start + "generate_handler![".len()..];
    let end = body
        .find(']')
        .expect("the generate_handler! block must be closed");
    body[..end]
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(str::to_owned)
        .collect()
}

/// Extracts the wire command names from the frontend `COMMANDS` map.
fn frontend_commands() -> BTreeSet<String> {
    let source = read("../src/ipc.ts");
    let start = source
        .find("export const COMMANDS = {")
        .expect("src/ipc.ts must declare a COMMANDS map");
    let body = &source[start..];
    let end = body
        .find("} as const;")
        .expect("the COMMANDS map must be closed");
    body[..end]
        .lines()
        .filter_map(|line| {
            let (_, value) = line.split_once(": \"")?;
            let (command, _) = value.split_once('"')?;
            Some(command.to_owned())
        })
        .collect()
}

/// Command names that have a generated permission definition on disk.
fn permission_commands() -> BTreeSet<String> {
    let directory = repository_path("permissions/autogenerated");
    fs::read_dir(&directory)
        .unwrap_or_else(|error| panic!("failed to list {}: {error}", directory.display()))
        .filter_map(|entry| {
            let path = entry
                .expect("failed to read a permission directory entry")
                .path();
            if path.extension()? != "toml" {
                return None;
            }
            Some(path.file_stem()?.to_str()?.to_owned())
        })
        .collect()
}

/// Commands granted by at least one capability, converted back from the
/// `allow-<kebab-name>` identifier to the underlying command name.
fn granted_commands() -> BTreeSet<String> {
    let directory = repository_path("capabilities");
    let mut granted = BTreeSet::new();
    for entry in fs::read_dir(&directory)
        .unwrap_or_else(|error| panic!("failed to list {}: {error}", directory.display()))
    {
        let path = entry
            .expect("failed to read a capability directory entry")
            .path();
        if path.extension().is_none_or(|extension| extension != "json") {
            continue;
        }
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
        let mut rest = source.as_str();
        // Core plugin permissions ("core:event:allow-listen") are namespaced and
        // are not app commands, so only bare "allow-*" entries are collected.
        while let Some(offset) = rest.find("\"allow-") {
            rest = &rest[offset + "\"allow-".len()..];
            let Some((identifier, remainder)) = rest.split_once('"') else {
                break;
            };
            rest = remainder;
            granted.insert(identifier.replace('-', "_"));
        }
    }
    granted
}

fn registered_commands() -> BTreeSet<String> {
    orange_domain::REGISTERED_COMMANDS
        .iter()
        .map(|command| (*command).to_owned())
        .collect()
}

fn report(missing: &BTreeSet<String>) -> String {
    missing
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>()
        .join(", ")
}

/// The assertion that would have caught the twelve-command outage: anything the
/// shell can invoke must be granted by a capability, or the user only ever sees
/// "操作未完成，请稍后重试".
#[test]
fn every_ui_callable_command_is_granted_by_a_capability() {
    let callable: BTreeSet<String> = desktop_handler_commands()
        .intersection(&frontend_commands())
        .cloned()
        .collect();
    let ungranted: BTreeSet<String> = callable.difference(&granted_commands()).cloned().collect();
    assert!(
        ungranted.is_empty(),
        "these commands are invoked by the shell but no capability grants them, so \
         Tauri will reject them at runtime with an unparseable error: {}. \
         Add each to REGISTERED_COMMANDS in crates/orange-domain/src/ipc.rs, rebuild \
         to generate its permission TOML, then grant \"allow-<kebab-name>\" in \
         src-tauri/capabilities/.",
        report(&ungranted)
    );
}

/// `build.rs` generates one permission TOML per entry in `REGISTERED_COMMANDS`,
/// and those files are committed. A missing file means the tree was not rebuilt
/// after the list changed.
#[test]
fn registered_commands_have_generated_permissions() {
    let permissions = permission_commands();
    let missing: BTreeSet<String> = registered_commands()
        .difference(&permissions)
        .cloned()
        .collect();
    assert!(
        missing.is_empty(),
        "no generated permission file for: {}. Run `cargo check -p orange-app` and \
         commit src-tauri/permissions/autogenerated/.",
        report(&missing)
    );

    let orphaned: BTreeSet<String> = permissions
        .difference(&registered_commands())
        .cloned()
        .collect();
    assert!(
        orphaned.is_empty(),
        "these permission files no longer correspond to a registered command and \
         should be deleted: {}",
        report(&orphaned)
    );
}

/// A capability may only grant commands that actually exist, otherwise the grant
/// silently does nothing.
#[test]
fn capability_grants_reference_real_commands() {
    let handler = desktop_handler_commands();
    let unknown: BTreeSet<String> = granted_commands().difference(&handler).cloned().collect();
    assert!(
        unknown.is_empty(),
        "these capability grants do not match any command in the invoke_handler: {}",
        report(&unknown)
    );
}

/// Both directions between the Rust handler and the frontend command map, so a
/// renamed command cannot drift on one side only.
#[test]
fn handler_and_frontend_command_maps_agree() {
    let handler = desktop_handler_commands();
    let frontend = frontend_commands();

    let frontend_only: BTreeSet<String> = frontend.difference(&handler).cloned().collect();
    assert!(
        frontend_only.is_empty(),
        "src/ipc.ts invokes commands that the Rust invoke_handler does not expose: {}",
        report(&frontend_only)
    );

    let handler_only: BTreeSet<String> = handler.difference(&frontend).cloned().collect();
    assert!(
        handler_only.is_empty(),
        "these commands are registered in the invoke_handler but unreachable from \
         src/ipc.ts; wire them up or remove them: {}",
        report(&handler_only)
    );
}

/// Guards the parsers themselves: if a refactor changes the shape of any source
/// file, the extractors above would silently return an empty set and every
/// assertion would pass vacuously.
#[test]
fn command_extractors_find_a_plausible_number_of_entries() {
    let expected = registered_commands().len();
    assert!(
        expected > 40,
        "REGISTERED_COMMANDS looks implausibly short ({expected}); the list or this \
         test is wrong"
    );
    for (label, count) in [
        ("invoke_handler", desktop_handler_commands().len()),
        ("src/ipc.ts COMMANDS", frontend_commands().len()),
        ("permission TOMLs", permission_commands().len()),
        ("capability grants", granted_commands().len()),
    ] {
        assert_eq!(
            count, expected,
            "{label} lists {count} commands but REGISTERED_COMMANDS has {expected}; \
             either a command is missing from one of the five lists or the parser in \
             this test no longer matches the source layout"
        );
    }
}
