from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from pathlib import Path, PurePosixPath
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
POLICY_PATH = Path("security/tauri-capabilities.json")
REPORT_PATH = Path("target/tauri-capabilities/report.json")
CAPABILITY_DIRECTORY = "src-tauri/capabilities"
PERMISSION_DIRECTORY = "src-tauri/permissions/autogenerated"
CAPABILITY_SCHEMA = "../gen/schemas/desktop-schema.json"
FORBIDDEN_PERMISSION_PREFIXES = ("dialog:", "fs:", "shell:")
PLATFORMS = {"android", "iOS", "linux", "macOS", "windows"}
POLICY_FIELDS = {
    "schema_version",
    "capability_directory",
    "permission_directory",
    "forbidden_permission_prefixes",
    "capabilities",
    "permission_definitions",
}
CAPABILITY_BASELINE_FIELDS = {"identifier", "windows", "platforms", "permissions"}
PERMISSION_BASELINE_FIELDS = {"path", "command"}
COMMAND_PATTERN = re.compile(r"^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$")


class DuplicateJsonKeyError(ValueError):
    pass


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise DuplicateJsonKeyError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_reject_duplicate_keys)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalized_path(value: object) -> PurePosixPath | None:
    if not isinstance(value, str) or not value or "\\" in value:
        return None
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        return None
    return path


def exact_fields(value: object, expected: set[str], label: str, errors: list[str]) -> bool:
    if not isinstance(value, dict):
        errors.append(f"{label} must be an object")
        return False
    missing = sorted(expected - set(value))
    extra = sorted(set(value) - expected)
    if missing:
        errors.append(f"{label} missing fields: {', '.join(missing)}")
    if extra:
        errors.append(f"{label} has unsupported fields: {', '.join(extra)}")
    return not missing and not extra


def string_list(
    value: object,
    label: str,
    errors: list[str],
    *,
    allow_empty: bool = False,
) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        errors.append(f"{label} must be an array of non-empty strings")
        return []
    if not value and not allow_empty:
        errors.append(f"{label} cannot be empty")
    if value != sorted(set(value)):
        errors.append(f"{label} must be sorted and unique")
    return list(value)


def repository_file(root: Path, value: object, label: str, errors: list[str]) -> Path | None:
    relative = normalized_path(value)
    if relative is None:
        errors.append(f"{label} must be a normalized relative POSIX path")
        return None
    candidate = root.joinpath(*relative.parts)
    if not candidate.is_file():
        errors.append(f"{label} is missing: {relative.as_posix()}")
        return None
    if candidate.is_symlink():
        errors.append(f"{label} cannot be a symlink: {relative.as_posix()}")
        return None
    try:
        candidate.resolve(strict=True).relative_to(root.resolve(strict=True))
    except (OSError, ValueError):
        errors.append(f"{label} escapes the repository: {relative.as_posix()}")
        return None
    return candidate


def validate_policy(policy: object) -> list[str]:
    errors: list[str] = []
    if not exact_fields(policy, POLICY_FIELDS, "policy", errors):
        return errors
    assert isinstance(policy, dict)
    if policy["schema_version"] != 1:
        errors.append("policy.schema_version must be 1")
    if policy["capability_directory"] != CAPABILITY_DIRECTORY:
        errors.append(f"policy.capability_directory must be {CAPABILITY_DIRECTORY}")
    if policy["permission_directory"] != PERMISSION_DIRECTORY:
        errors.append(f"policy.permission_directory must be {PERMISSION_DIRECTORY}")
    if policy["forbidden_permission_prefixes"] != list(FORBIDDEN_PERMISSION_PREFIXES):
        errors.append("policy.forbidden_permission_prefixes cannot be weakened")

    capabilities = policy["capabilities"]
    if not isinstance(capabilities, dict) or not capabilities:
        errors.append("policy.capabilities must be a non-empty object")
        capabilities = {}
    identifiers: set[str] = set()
    granted_custom_permissions: set[str] = set()
    for path_value, expected in capabilities.items():
        label = f"policy.capabilities[{path_value}]"
        relative = normalized_path(path_value)
        if (
            relative is None
            or relative.parent.as_posix() != CAPABILITY_DIRECTORY
            or relative.suffix != ".json"
        ):
            errors.append(f"{label} path must be a direct JSON child of {CAPABILITY_DIRECTORY}")
        if not exact_fields(expected, CAPABILITY_BASELINE_FIELDS, label, errors):
            continue
        identifier = expected["identifier"]
        if not isinstance(identifier, str) or not identifier:
            errors.append(f"{label}.identifier must be a non-empty string")
        elif identifier in identifiers:
            errors.append(f"duplicate capability identifier in policy: {identifier}")
        else:
            identifiers.add(identifier)
        string_list(expected["windows"], f"{label}.windows", errors)
        platforms = string_list(
            expected["platforms"], f"{label}.platforms", errors, allow_empty=True
        )
        invalid_platforms = sorted(set(platforms) - PLATFORMS)
        if invalid_platforms:
            errors.append(f"{label}.platforms contains invalid values: {invalid_platforms}")
        permissions = string_list(expected["permissions"], f"{label}.permissions", errors)
        forbidden = [
            permission
            for permission in permissions
            if permission.startswith(FORBIDDEN_PERMISSION_PREFIXES)
        ]
        if forbidden:
            errors.append(f"{label} grants forbidden file, dialog, or shell access: {forbidden}")
        granted_custom_permissions.update(
            permission for permission in permissions if not permission.startswith("core:")
        )

    definitions = policy["permission_definitions"]
    if not isinstance(definitions, dict) or not definitions:
        errors.append("policy.permission_definitions must be a non-empty object")
        definitions = {}
    definition_paths: set[str] = set()
    for identifier, expected in definitions.items():
        label = f"policy.permission_definitions[{identifier}]"
        if not exact_fields(expected, PERMISSION_BASELINE_FIELDS, label, errors):
            continue
        path_value = expected["path"]
        relative = normalized_path(path_value)
        if (
            relative is None
            or relative.parent.as_posix() != PERMISSION_DIRECTORY
            or relative.suffix != ".toml"
        ):
            errors.append(f"{label}.path must be a direct TOML child of {PERMISSION_DIRECTORY}")
        elif path_value in definition_paths:
            errors.append(f"duplicate permission definition path: {path_value}")
        else:
            definition_paths.add(path_value)
        command = expected["command"]
        if not isinstance(command, str) or COMMAND_PATTERN.fullmatch(command) is None:
            errors.append(f"{label}.command must be a snake_case command")
        elif identifier != f"allow-{command.replace('_', '-')}":
            errors.append(f"{label} identifier does not match command {command}")

    missing_definitions = sorted(granted_custom_permissions - set(definitions))
    unused_definitions = sorted(set(definitions) - granted_custom_permissions)
    if missing_definitions:
        errors.append(f"custom capability permissions lack definitions: {missing_definitions}")
    if unused_definitions:
        errors.append(f"permission definitions are not granted by a capability: {unused_definitions}")
    return errors


def inventory(root: Path, directory: str, suffix: str) -> set[str]:
    base = root.joinpath(*PurePosixPath(directory).parts)
    if not base.is_dir() or base.is_symlink():
        return set()
    return {
        path.relative_to(root).as_posix()
        for path in base.rglob(f"*{suffix}")
        if path.is_file()
    }


def compare_inventory(
    actual: set[str], expected: set[str], label: str, errors: list[str]
) -> None:
    unregistered = sorted(actual - expected)
    missing = sorted(expected - actual)
    if unregistered:
        errors.append(f"unregistered {label} files: {unregistered}")
    if missing:
        errors.append(f"registered {label} files are missing: {missing}")


def audit_capability(
    root: Path, path_value: str, expected: dict[str, Any], errors: list[str]
) -> dict[str, Any] | None:
    path = repository_file(root, path_value, f"capability {path_value}", errors)
    if path is None:
        return None
    try:
        document = load_json(path)
    except (json.JSONDecodeError, OSError, DuplicateJsonKeyError) as error:
        errors.append(f"cannot parse capability {path_value}: {error}")
        return None
    expected_fields = {"$schema", "identifier", "description", "windows", "permissions"}
    if expected["platforms"]:
        expected_fields.add("platforms")
    exact_fields(document, expected_fields, f"capability {path_value}", errors)
    if not isinstance(document, dict):
        return None
    if document.get("$schema") != CAPABILITY_SCHEMA:
        errors.append(f"capability {path_value} must use schema {CAPABILITY_SCHEMA}")
    if not isinstance(document.get("description"), str) or not document.get("description"):
        errors.append(f"capability {path_value}.description must be a non-empty string")
    actual = {
        "identifier": document.get("identifier"),
        "windows": document.get("windows"),
        "platforms": document.get("platforms", []),
        "permissions": document.get("permissions"),
    }
    if actual != expected:
        errors.append(f"capability baseline drift: {path_value}")
    permissions = document.get("permissions")
    if isinstance(permissions, list):
        forbidden = [
            permission
            for permission in permissions
            if isinstance(permission, str)
            and permission.startswith(FORBIDDEN_PERMISSION_PREFIXES)
        ]
        if forbidden:
            errors.append(
                f"capability {path_value} grants forbidden file, dialog, or shell access: {forbidden}"
            )
    return {
        "path": path_value,
        "sha256": sha256(path),
        **actual,
    }


def audit_permission_definition(
    root: Path,
    identifier: str,
    expected: dict[str, str],
    errors: list[str],
) -> dict[str, str] | None:
    path_value = expected["path"]
    path = repository_file(root, path_value, f"permission definition {path_value}", errors)
    if path is None:
        return None
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        errors.append(f"cannot parse permission definition {path_value}: {error}")
        return None
    if not exact_fields(document, {"permission"}, f"permission definition {path_value}", errors):
        return None
    entries = document["permission"]
    if not isinstance(entries, list) or len(entries) != 2:
        errors.append(f"permission definition {path_value} must contain one allow and one deny entry")
        return None
    by_identifier = {
        entry.get("identifier"): entry for entry in entries if isinstance(entry, dict)
    }
    allow_entry = by_identifier.get(identifier)
    deny_identifier = identifier.replace("allow-", "deny-", 1)
    deny_entry = by_identifier.get(deny_identifier)
    command = expected["command"]
    for entry, entry_identifier, mode in (
        (allow_entry, identifier, "allow"),
        (deny_entry, deny_identifier, "deny"),
    ):
        label = f"permission definition {path_value} entry {entry_identifier}"
        if not exact_fields(entry, {"identifier", "description", "commands"}, label, errors):
            continue
        assert isinstance(entry, dict)
        if not isinstance(entry["description"], str) or not entry["description"]:
            errors.append(f"{label}.description must be a non-empty string")
        if entry["commands"] != {mode: [command]}:
            errors.append(f"{label} must map only {mode} to {command}")
    return {
        "identifier": identifier,
        "path": path_value,
        "command": command,
        "sha256": sha256(path),
    }


def audit_workspace(root: Path = ROOT, policy_path: Path | None = None) -> dict[str, Any]:
    root = root.resolve(strict=True)
    selected_policy = policy_path or root / POLICY_PATH
    if not selected_policy.is_absolute():
        selected_policy = root / selected_policy
    policy = load_json(selected_policy)
    errors = validate_policy(policy)
    if not isinstance(policy, dict):
        capabilities: dict[str, Any] = {}
        definitions: dict[str, Any] = {}
    else:
        capabilities = policy.get("capabilities", {})
        definitions = policy.get("permission_definitions", {})
        if not isinstance(capabilities, dict):
            capabilities = {}
        if not isinstance(definitions, dict):
            definitions = {}

    compare_inventory(
        inventory(root, CAPABILITY_DIRECTORY, ".json"),
        set(capabilities),
        "capability",
        errors,
    )
    expected_definition_paths = {
        value["path"]
        for value in definitions.values()
        if isinstance(value, dict) and isinstance(value.get("path"), str)
    }
    compare_inventory(
        inventory(root, PERMISSION_DIRECTORY, ".toml"),
        expected_definition_paths,
        "permission definition",
        errors,
    )

    capability_reports = []
    for path_value in sorted(capabilities):
        expected = capabilities[path_value]
        if isinstance(expected, dict) and exact_fields(
            expected, CAPABILITY_BASELINE_FIELDS, f"capability baseline {path_value}", errors
        ):
            report = audit_capability(root, path_value, expected, errors)
            if report is not None:
                capability_reports.append(report)

    definition_reports = []
    for identifier in sorted(definitions):
        expected = definitions[identifier]
        if isinstance(expected, dict) and exact_fields(
            expected,
            PERMISSION_BASELINE_FIELDS,
            f"permission baseline {identifier}",
            errors,
        ):
            report = audit_permission_definition(root, identifier, expected, errors)
            if report is not None:
                definition_reports.append(report)

    return {
        "schema_version": 1,
        "passed": not errors,
        "policy": selected_policy.relative_to(root).as_posix(),
        "capability_count": len(capability_reports),
        "permission_definition_count": len(definition_reports),
        "capabilities": capability_reports,
        "permission_definitions": definition_reports,
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit the current Orange Tauri capability baseline")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--policy", type=Path)
    parser.add_argument("--report", type=Path, default=REPORT_PATH)
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    report_path = arguments.report
    if not report_path.is_absolute():
        report_path = root / report_path
    try:
        report = audit_workspace(root, arguments.policy)
    except (json.JSONDecodeError, OSError, ValueError) as error:
        report = {
            "schema_version": 1,
            "passed": False,
            "capability_count": 0,
            "permission_definition_count": 0,
            "capabilities": [],
            "permission_definitions": [],
            "errors": [str(error)],
        }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    if report["passed"]:
        print(
            "Tauri capability baseline passed: "
            f"{report['capability_count']} capabilities, "
            f"{report['permission_definition_count']} permission definitions"
        )
        return 0
    for error in report["errors"]:
        print(f"ERROR: {error}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
