import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


MODULE_PATH = Path(__file__).with_name("check_tauri_capabilities.py")
SPEC = importlib.util.spec_from_file_location("check_tauri_capabilities", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
capabilities = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = capabilities
SPEC.loader.exec_module(capabilities)


class TauriCapabilityTests(unittest.TestCase):
    def setUp(self) -> None:
        self.directory = tempfile.TemporaryDirectory()
        self.root = Path(self.directory.name)
        (self.root / "security").mkdir()
        (self.root / "src-tauri" / "capabilities").mkdir(parents=True)
        (self.root / "src-tauri" / "permissions" / "autogenerated").mkdir(parents=True)
        self.capability_path = self.root / "src-tauri" / "capabilities" / "default.json"
        self.permission_path = (
            self.root / "src-tauri" / "permissions" / "autogenerated" / "get_state.toml"
        )
        self.policy = {
            "schema_version": 1,
            "capability_directory": "src-tauri/capabilities",
            "permission_directory": "src-tauri/permissions/autogenerated",
            "forbidden_permission_prefixes": ["dialog:", "fs:", "shell:"],
            "capabilities": {
                "src-tauri/capabilities/default.json": {
                    "identifier": "main-window",
                    "windows": ["main"],
                    "platforms": [],
                    "permissions": ["allow-get-state", "core:event:allow-listen"],
                }
            },
            "permission_definitions": {
                "allow-get-state": {
                    "path": "src-tauri/permissions/autogenerated/get_state.toml",
                    "command": "get_state",
                }
            },
        }
        self.capability = {
            "$schema": "../gen/schemas/desktop-schema.json",
            "identifier": "main-window",
            "description": "Minimum test capability",
            "windows": ["main"],
            "permissions": ["allow-get-state", "core:event:allow-listen"],
        }
        self.write_fixture()

    def tearDown(self) -> None:
        self.directory.cleanup()

    def write_fixture(self) -> None:
        (self.root / "security" / "tauri-capabilities.json").write_text(
            json.dumps(self.policy, indent=2) + "\n", encoding="utf-8"
        )
        self.capability_path.write_text(
            json.dumps(self.capability, indent=2) + "\n", encoding="utf-8"
        )
        self.permission_path.write_text(
            """# Automatically generated - DO NOT EDIT!

[[permission]]
identifier = "allow-get-state"
description = "Allows get_state."
commands.allow = ["get_state"]

[[permission]]
identifier = "deny-get-state"
description = "Denies get_state."
commands.deny = ["get_state"]
""",
            encoding="utf-8",
        )

    def audit(self) -> dict[str, object]:
        return capabilities.audit_workspace(self.root)

    def test_valid_fixture_and_repository_baseline_pass(self) -> None:
        report = self.audit()
        self.assertTrue(report["passed"], report["errors"])
        self.assertEqual(report["capability_count"], 1)
        self.assertEqual(report["permission_definition_count"], 1)

        repository_report = capabilities.audit_workspace(capabilities.ROOT)
        self.assertTrue(repository_report["passed"], repository_report["errors"])
        self.assertEqual(repository_report["capability_count"], 5)
        self.assertEqual(repository_report["permission_definition_count"], 17)

    def test_unregistered_capability_and_permission_files_fail_closed(self) -> None:
        (self.capability_path.parent / "extra.json").write_text("{}\n", encoding="utf-8")
        (self.permission_path.parent / "extra.toml").write_text(
            "permission = []\n", encoding="utf-8"
        )
        errors = "\n".join(self.audit()["errors"])
        self.assertIn("unregistered capability files", errors)
        self.assertIn("unregistered permission definition files", errors)

    def test_capability_drift_and_forbidden_permissions_are_rejected(self) -> None:
        self.capability["permissions"].append("fs:allow-read-text-file")
        self.write_fixture()
        errors = "\n".join(self.audit()["errors"])
        self.assertIn("capability baseline drift", errors)
        self.assertIn("forbidden file, dialog, or shell access", errors)

    def test_policy_cannot_remove_forbidden_prefixes(self) -> None:
        self.policy["forbidden_permission_prefixes"] = []
        self.write_fixture()
        self.assertIn(
            "policy.forbidden_permission_prefixes cannot be weakened",
            self.audit()["errors"],
        )

    def test_toml_allow_and_deny_command_mapping_is_exact(self) -> None:
        self.permission_path.write_text(
            self.permission_path.read_text(encoding="utf-8").replace(
                'commands.allow = ["get_state"]', 'commands.allow = ["other_command"]'
            ),
            encoding="utf-8",
        )
        errors = "\n".join(self.audit()["errors"])
        self.assertIn("must map only allow to get_state", errors)

    def test_duplicate_json_keys_fail_and_cli_still_writes_report(self) -> None:
        self.capability_path.write_text(
            """{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "main-window",
  "identifier": "other-window",
  "description": "Duplicate identifier",
  "windows": ["main"],
  "permissions": ["allow-get-state", "core:event:allow-listen"]
}
""",
            encoding="utf-8",
        )
        report_path = self.root / "target" / "audit.json"
        result = subprocess.run(
            [
                sys.executable,
                str(MODULE_PATH),
                "--root",
                str(self.root),
                "--report",
                str(report_path),
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 1)
        report = json.loads(report_path.read_text(encoding="utf-8"))
        self.assertFalse(report["passed"])
        self.assertIn("duplicate JSON key", "\n".join(report["errors"]))


if __name__ == "__main__":
    unittest.main()
