[package]
name = "orange-bootstrap-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "orange-bootstrap-crypto"
path = "src/main.rs"

[dependencies]
orange-bootstrap = { path = "../../crates/orange-bootstrap" }
serde_json.workspace = true
zeroize.workspace = true
