version: "1.0"
name: orange-pr-pipeline
displayName: Orange PR Pipeline
stages:
  - stage:
    name: portable_quality
    displayName: Portable Quality
    strategy: fast
    trigger: auto
    steps:
      - step: build@python
        name: portable_quality
        displayName: Portable Quality
        pythonVersion: 3.9
        commands:
          - bash scripts/ci/run-gitee-cloud.sh
        artifacts:
          - name: ORANGE_QUALITY_ARTIFACTS
            path:
              - ./artifacts
triggers:
  pr:
    branches:
      include:
        - master
        - main
