export const SHELL_TEXT = {
  startupTitle: "正在启动安全服务",
  startupDetail: "正在确认本机安全状态",
  startupErrorTitle: "安全服务暂不可用",
  startupErrorDetail: "Orange 无法完成安全初始化。",
  retry: "重试",
  emptyTitle: "暂无可用内容",
  emptyDetail: "当前账户下没有可显示的项目。",
  backHome: "返回首页",
  workspace: "工作台",
  connection: "连接",
  subscription: "订阅",
  nodes: "节点",
  account: "账户",
  settings: "设置",
  navigation: "主导航",
  serviceReady: "安全服务可用",
  currentEnvironment: "当前环境",
  notification: "通知",
  notificationAvailable: "通知，有公告",
  serviceNotice: "服务公告",
  noNotifications: "暂无新通知",
  loadingNotifications: "正在加载通知",
  notificationsUnavailable: "通知暂时无法加载",
  loginTitle: "登录 Orange",
  loginSubtitle: "使用账户继续",
  forgotPassword: "忘记密码",
  forgotPasswordTitle: "重置密码",
  forgotPasswordSubtitle: "验证邮箱并设置新密码",
  registerTitle: "创建账户",
  registerSubtitle: "完成账户信息",
  email: "邮箱",
  emailPlaceholder: "name@example.com",
  password: "密码",
  newPassword: "新密码",
  confirmPassword: "确认密码",
  emailCode: "邮箱验证码",
  emailCodePlaceholder: "6 位数字验证码",
  sendEmailCode: "发送验证码",
  sendingEmailCode: "正在发送",
  emailCodeSent: "验证码已发送，请检查邮箱。",
  inviteCode: "邀请码",
  inviteOptional: "邀请码（可选）",
  inviteRequired: "请输入邀请码。",
  showPassword: "显示密码",
  hidePassword: "隐藏密码",
  login: "登录",
  loggingIn: "正在登录",
  resetPassword: "重置密码",
  resettingPassword: "正在重置",
  passwordResetSuccess: "密码已重置，请重新登录。",
  backToLogin: "返回登录",
  register: "注册",
  registering: "正在注册",
  createAccount: "创建账户",
  alreadyRegistered: "已有账户",
  maintenanceTitle: "服务维护中",
  maintenanceDetail: "当前暂不接受账户操作。",
  unverifiedTitle: "登录状态尚未验证",
  unverifiedDetail: "已保存的账户暂时无法通过安全服务验证。",
  retryVerification: "重新验证",
  emailInvalid: "请输入有效邮箱。",
  emailCodeInvalid: "请输入 6 位数字验证码。",
  passwordInvalid: "密码需为 8 至 128 字节且不能包含控制字符。",
  inviteInvalid: "邀请码只能包含字母、数字、下划线和连字符。",
  passwordMismatch: "两次输入的密码不一致。",
  requestInvalid: "请检查输入内容。",
  operationFailed: "操作未完成，请稍后重试。",
  trayActionFailed: "托盘操作未完成，请在 Orange 窗口中重试。",
  trayExitFailed: "无法安全退出，连接仍由 Orange 管理，请重试。",
  loginSuccess: "登录成功",
  registerSuccess: "注册成功",
  logoutSuccess: "已安全退出",
  dismiss: "关闭",
  accountTitle: "账户",
  accountSubtitle: "当前登录信息",
  accountStatus: "账户状态",
  active: "正常",
  disabled: "已停用",
  unknown: "未知",
  logout: "退出登录",
  logoutDialogTitle: "确认退出登录",
  logoutDialogDetail: "Orange 将先停止当前连接，再清理本机账户凭据。",
  cancel: "取消",
  confirmLogout: "确认退出",
  loggingOut: "正在退出",
  safeFailureTitle: "页面暂时无法显示",
  safeFailureDetail: "Orange 已阻止异常内容继续运行。",
  retryPage: "重新加载页面",
  lightTheme: "亮色",
  darkTheme: "暗色",
  switchToLight: "切换到亮色模式",
  switchToDark: "切换到暗色模式",
} as const;
