export const UI_TEXT = {
  brand: "Orange",
  workspace: "工作台",
  connection: "连接",
  navigation: "主导航",
  home: "首页",
  subscription: "订阅",
  nodes: "节点",
  account: "账户",
  settings: "设置",
  currentPage: "当前页面",
  brandSubtitle: "安全连接",
  environment: "当前环境",
  serviceUnconfigured: "服务未配置",
  unavailable: "未配置",
  subscriptionStatus: "订阅状态",
  subscriptionEmpty: "尚未配置可用订阅",
  subscriptionEmptyDetail: "完成账户配置后，这里将显示订阅状态与有效期。",
  subscriptionReady: "订阅已配置",
  subscriptionReadyDetail: "本机已加载可用节点，可随时建立安全连接。",
  subscriptionExpired: "订阅已到期",
  subscriptionExpiredDetail: "续费并刷新订阅后才能建立新连接。",
  subscriptionExhausted: "流量已用尽",
  subscriptionExhaustedDetail: "补充流量并刷新订阅后才能建立新连接。",
  connectedWithExpiredSubscription:
    "当前连接仍在线；断开后需续费并刷新订阅才能重连。",
  connectedWithExhaustedSubscription:
    "当前连接仍在线；断开后需补充流量并刷新订阅才能重连。",
  connectUnavailable: "连接不可用",
  disconnect: "断开连接",
  retryConnection: "重试连接",
  connectionActionPending: "正在处理",
  connectionActionFailed: "连接操作未完成，请重试。",
  readingConnection: "正在读取连接状态",
  connectionStateUnavailable: "连接状态暂不可用",
  connectionStateUnavailableDetail: "本机服务暂未返回状态",
  disconnected: "当前未连接",
  waitingForConfiguration: "等待有效配置",
  validatingConfiguration: "正在验证配置",
  validatingConfigurationDetail: "正在检查本机连接配置",
  permissionRequired: "需要系统授权",
  permissionRequiredDetail: "完成系统授权后才能建立连接",
  connecting: "正在连接",
  connectingDetail: "正在启动本机安全连接",
  connected: "已连接",
  connectedDetail: "本机流量正在受保护",
  connectedTrafficUnavailableDetail: "连接在线，流量状态暂不可用",
  disconnecting: "正在断开",
  disconnectingDetail: "正在安全释放本机连接",
  connectionFailed: "连接失败",
  connectionFailedDetail: "本机连接服务需要恢复",
  restoringConnection: "正在恢复",
  restoringConnectionDetail: "正在恢复上一个可用配置",
  upload: "上传",
  download: "下载",
  zeroSpeed: "0 B/s",
  connectionOptions: "连接选项",
  routeMode: "路由模式",
  smartRoute: "智能路由",
  selectedNode: "当前节点",
  noNodeSelected: "未选择",
  nodeSelected: "已选择",
  configurationRequired: "配置订阅后可用",
  liveConnectionState: "本机连接状态",
  notification: "通知",
  noNotifications: "暂无新通知",
  switchToLight: "切换到亮色模式",
  switchToDark: "切换到暗色模式",
  theme: "主题",
  lightTheme: "亮色",
  darkTheme: "暗色",
} as const;
