export const UI_TEXT = {
  brand: "Orange",
  workspace: "工作台",
  connection: "连接",
  navigation: "主导航",
  home: "首页",
  subscription: "订阅",
  nodes: "节点",
  account: "账户",
  settings: "设置",
  currentPage: "当前页面",
  brandSubtitle: "安全连接",
  environment: "当前环境",
  serviceUnconfigured: "服务未配置",
  unavailable: "未配置",
  subscriptionStatus: "订阅状态",
  subscriptionEmpty: "尚未配置可用订阅",
  subscriptionEmptyDetail: "完成账户配置后，这里将显示订阅状态与有效期。",
  connectUnavailable: "连接不可用",
  disconnected: "当前未连接",
  waitingForConfiguration: "等待有效配置",
  upload: "上传",
  download: "下载",
  zeroSpeed: "0 B/s",
  connectionOptions: "连接选项",
  routeMode: "路由模式",
  smartRoute: "智能路由",
  selectedNode: "当前节点",
  noNodeSelected: "未选择",
  configurationRequired: "配置订阅后可用",
  notification: "通知",
  noNotifications: "暂无新通知",
  switchToLight: "切换到亮色模式",
  switchToDark: "切换到暗色模式",
  theme: "主题",
  lightTheme: "亮色",
  darkTheme: "暗色",
} as const;
